language: java
jdk: oraclejdk8
services:
- docker
before_install:
- chmod +x mvnw
- ls $TRAVIS_BUILD_DIR
- echo $GPG_KEY | gpg --passphrase-fd 0 $TRAVIS_BUILD_DIR/src/main/resources/firebase-adminsdk.json.gpg
- ls $TRAVIS_BUILD_DIR/src/main/resources
script:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V"
after_success:
- mvn clean test jacoco:report coveralls:report
- ./mvnw dockerfile:build
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push $DOCKER_REPO
cache:
  directories:
  - "$HOME/.m2"
env:
#  global:
#    secure: Uifod8oP3DUaWGyqNG1FEvmrMyhaUDMPLQ0kOmhH0IfTfyh+aAAqBg1BwlLweu6C6JBJUGQmely8IMRvKlBlyVsuBZ6KWPNRHyjEea/CCz1I2NMQPBlud+D3FzDl5s8s1kYZIWn1AUZ7Ccg3z0PcU2Og5QtM5Lt4QbIdgpdS9O11UfAKhJTMRnhYp15zM/eiQiplD+wQg/W66pqYufNTXxUGRRQMd0cuaEsTctUn8TAAzycDXI0NAHC2sScfG8YN0Kx4lZhE5iRwaRGQ8Y50nAphZp9ik29od2zsG/GtgpINOqJAPCD4PMFf2Lzi/Ae+yNqvxG3s5co7Xm3+xc8ybbOlFjCeeIsMC8ZXx8kS0zIN+wYMVb8nJV+3yV8hcSyCp/72CcvFfEJMWAryWomK/FUqnRdDKFbu4wsMMazUTayhBpOq7Yf15fF88L4KcLXBTd+xpdCcSvFXSBlVOBjeio82y+RHj2Bihkmypaof1ZKYyzawcvd3oUIgqhQ22kgDLkBRqqgvMbjAEIBKSiIp/c51dCsqfcNXJDzSnwMGZOgpp97QKKt9hClRLBgNeG1ZOXiGiFiwWWQ1fjj6vP28Yrro/kvlILjxd9PhwGvHMkbB3sZvHbRaSDHpFxcXGjM56E86quRSmWSga254jkDoFDapHrTAlwilGzK8ICnL4fQ=
  matrix:
#    firebase.privatekey: asdfasfd
    - secure: Ce38Z3S56kQNIIhSDFmqt7P/hxp+mqqEWbV+LvOaoc085uncXiQk+7Skm/yct+Xe9sZQ8ttay5fdnq/buAQTCF8Qhb89+QpKS1p8CA8wnPonPHrvHqx8XfJWCNu0q31SnJ4kp/KiJLFmVkpXS9NzLNnALQgEjU441y5Ak0MLbn4L66rdlIp/7TaQvh/p4fsU8mCzuMw4WMqs97oFKrTTyuSp9/1cObAgLTVw4/H3CgkVo1FkUVGgMWd47Q6GFjcayE9Y1h9k66T6IcNOMFArLfAa0Z91iVi19SS9ewPN6bS7Av7es25uml1j9LmVTt1RRv4QdxyAL9DgelNpZv7Qz54puUh6bdNvH/awSe5MgAmVnPsWqc5TP5pUlgKjHIqyjYxFlvWc1ZiU6hg34NbiH8kkuZ8FBLvWFgJrrU9p1fG1T/q2SgFSqEe6XUO9o+6+0q0TJSomAnBhaKS4K2mYPv3cTPxWZzeXc8/pKbJtYAhrpVYNHjr54llj60FBvkO4Q4/dNBrFLijbRvx3go5KbFO2H2uyKgm4oOp3WKTyIvqnSRQ6isRapnpz7vRVFyZ2saCrzU2IHjibobf8VJ4IAB0YxqPW4OZ5H7qMZFdxfV/bwa7WJssylizBylSGn+y8dUjTGtKxYLL3gGm0+zjoX3QFPsn3kM7PYQDyO6iHwKg=

