language: java
jdk: oraclejdk8

services:
  - docker

before_install:
  - chmod +x mvnw
  - echo $FIREBASE_ADMINSDK | base64 --decode -i > $TRAVIS_BUILD_DIR/src/main/resources/firebase-adminsdk.json
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_key -in $TRAVIS_BUILD_DIR/src/main/resources/firebase-adminsdk.json.enc -out $TRAVIS_BUILD_DIR/src/main/resources/firebase-adminsdk.json -d

script:
- mvn -N io.takari:maven:wrapper
- ./mvnw cobertura:cobertura
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

after_script:
  - docker image build -f Dockerfile_Travis . --tag $DOCKER_REPO
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $DOCKER_REPO
