language: java
jdk: oraclejdk8

services:
  - docker

before_install:
  - chmod +x mvnw

script:
- mvn -N io.takari:maven:wrapper
- ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- ./mvnw cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

deploy:
  - docker image build -f Dockerfile_Travis --tag $DOCKER_REPO
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $DOCKER_REPO