language: java
jdk: oraclejdk8
services:
- docker
before_install:
- chmod +x mvnw
- ls $TRAVIS_BUILD_DIR
- echo $GPG_KEY | gpg --passphrase-fd 0 $TRAVIS_BUILD_DIR/src/main/resources/firebase-adminsdk.json.gpg
- ls $TRAVIS_BUILD_DIR/src/main/resources
script:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V"
after_success:
- mvn clean test jacoco:report coveralls:report
- ./mvnw dockerfile:build
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push $DOCKER_REPO
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
    # below is a $GPG_KEY variable
    - secure: Uifod8oP3DUaWGyqNG1FEvmrMyhaUDMPLQ0kOmhH0IfTfyh+aAAqBg1BwlLweu6C6JBJUGQmely8IMRvKlBlyVsuBZ6KWPNRHyjEea/CCz1I2NMQPBlud+D3FzDl5s8s1kYZIWn1AUZ7Ccg3z0PcU2Og5QtM5Lt4QbIdgpdS9O11UfAKhJTMRnhYp15zM/eiQiplD+wQg/W66pqYufNTXxUGRRQMd0cuaEsTctUn8TAAzycDXI0NAHC2sScfG8YN0Kx4lZhE5iRwaRGQ8Y50nAphZp9ik29od2zsG/GtgpINOqJAPCD4PMFf2Lzi/Ae+yNqvxG3s5co7Xm3+xc8ybbOlFjCeeIsMC8ZXx8kS0zIN+wYMVb8nJV+3yV8hcSyCp/72CcvFfEJMWAryWomK/FUqnRdDKFbu4wsMMazUTayhBpOq7Yf15fF88L4KcLXBTd+xpdCcSvFXSBlVOBjeio82y+RHj2Bihkmypaof1ZKYyzawcvd3oUIgqhQ22kgDLkBRqqgvMbjAEIBKSiIp/c51dCsqfcNXJDzSnwMGZOgpp97QKKt9hClRLBgNeG1ZOXiGiFiwWWQ1fjj6vP28Yrro/kvlILjxd9PhwGvHMkbB3sZvHbRaSDHpFxcXGjM56E86quRSmWSga254jkDoFDapHrTAlwilGzK8ICnL4fQ=
    # below is a $firebase.privatekey
    - secure: eD1I7yuRJ2xU5nplfw4ziKxyx/zE2USHQCH09CikZMUro7h/psJ/zTpOmEa2amF2pmyQupGncAj03Sgmt0NW6aye4UxjiQdUvykcuHizwHO3uak9mJbbCqaV6dszweB5VY1Tl02jL4x3/cEveShrX+3xUMvlzYQc9TyjXSualVjtAOu8cE4bUE9fzlyywHsoKHkvBcYw3iWZNbKcvnyXbGzEUgWONcZ9FoYWFanUswZV3zvnf0tCjO8tqr65gd4QAFpLaK63lfeFdM3PIpDU3e4JBRHsnL5PSnuD7j36sJBwTJgoxufBa9t3B+FEFuwEvlXf9RX25nyMazYU3yQ0yGw+ZPRSXM5qfrVjTv18V32q4fEzCvhMhLVZ4egFIYScf8CDxoBJn/rm0AmtB9XF2YZmjZTqzsYDm/XqA8AeyDz77wptFgdoYgpmT/EUyz4AKZkieqFeyXc4mdrCq8DLc48UunUPx7OVcd5UhigU1G81ET3C3ib74mTbYW/Otfhi5nPgDe5hZ+fuzGGEQeGktmrl4xHeugTpu5Gr1hjWdAFi5YaJ/U8anBnV9CnqeYtD276mb8xWSBBA0TPl+x9TOWaxsXCY0Ys8o8juaY6OhH+Mboot5vC7Dm/AwE3urbTZzvzhXC0ZgFfBIdpkGfQxOfgEsDjPSR2bBhOTElpc1Sw=
