language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw

script:
- mvn -N io.takari:maven:wrapper
- ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- ./mvnw cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: oRejz3wX7w5CGas3VjJwV5ejT+AUeS29vtCjAhq5m3y3mCarX2l64sRbIwYJ4bheM8v8UK8oDckcC9w5XQUNti0ryjumdGwkWqAc3BTlK/grjr5mrNhFwAEE01OS7/TWmFwPFv6UXRJoa4W+Mr33GF4wXxP6/sVhpQgFYwoG/vcoyPpuzvZC+oU3utaWm+WtQXMSNYC6j+U/l6FAKUs55X3N8GSwVXOdQb6s2GBEM6KNQ/M/OLFLzFLT2QQauurQMewNgmpL9/90QMKRS+RvKJnu6Wxt2AfyYH+QriA2URVt8VCUMiVp+MffytpBHs7Ecedrq1wbLcrSZggomEinKrLoraiyv2BOk/uviS8G/1w2OcRNc7A3qzh+PqyqW/jLkATSHkPCmXX9K7GfM0vwdumakTEue163GqlFS9Pj4DnzUkc5xVcl68g34diSCpR3/oDo7BntwoYXZqNjPF6iS06xKsH0/CYY+EGAbvntCHfsAsD12tE7qYApt2R84g6ZpX19UCLo7Qpy3Yt0/Drnzt3TmDkHoGJQ5e1Y4HbdVmO5p5KmjaH5f2xp9bdJeeCbkPNv0KiQthuNoXinTN+ACpNpprJhhHw35XjHuOdS0dxFOZsig1/bd9l6BGQ/la0PvDSKRAuPd+enD99MYqsQX6QTY2MBF7x1iueu1T512Vo=
  secret_access_key:
    secure: eJA47znOucWfxvuQSPJ4r8gySeqZE5icekIz/DaFZOf15Nekj50xdKO8OAEqaaeG89qlHh7do9rOhSF68izwhx5/sri7+AdWc6zs/ssy1GFLfVU3/UC/Wr3MjEXofSGcjfz16rsOH7SFXB7+hWxmLxaTkBdZ9zWFe3NHYkbbY2Eozi96bqelvEeNvJLG+24vyMIBJTK51J8YowgiWmPmKojq7tKVXN9qoU8Vv05ZuCxEcBp2pPRK7RP25nsYyxeQe4xk33Dfgqm1blNwUI4o9DqxKPd5F9EvAGaOhpGmCFOEalB5u21KNEEwGb/wlp0fhTE74kptP4jIaU7Nc4t9Bbw+F2NC+S5pTfkUq+PqGi+0hFreGsID8UQaK4UPgHaTD1ac865LUG8ySUOZcisSfsJm+Vs41avps4SWW275cL2bVftK2Sg+5tLiuqd0x/vrQI93X4s8HKcJtA/cqqkjhzclMHAtnc1T+OHKF8xFzW3N8lnyG7O9q9xXX/irV4l3K60hEuyiPLcdhyuUdWEFh50h0TrEgHOacvqFx9LPFDTGKiBAIeeZMHQirn3lCf+fKgdcNQYDR+mZOwOMuy2RCJ7fXQs6w6Ywp3UgnO2jr9LLHZg5hzbcDxvLo/VPCi8cc7opy1c7Nrc0vxtl69le/2sg7QejP1xg6QkJGcjr8ag=
  region: "us-east-1"
  app: "receiptkeeper-data"
  env: "e-3cg9zhcqeh"
