FROM openjdk:8-jdk-alpine
VOLUME /tmp

ENV FIREBASE_CONFIG $FIREBASE_CONFIG

ARG restdata-0.0.2-SNAPSHOT.jar
COPY $TRAVIS_BUILD_DIR/target/restdata-0.0.2-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=prod","-jar","/app.jar"]