apiVersion: v1
kind: Service
metadata:
  name: rk-data-service
  labels:
    run: receiptkeeper-data
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: receiptkeeper-data

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rk-data
  name: rk-data-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30058
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: rk-data
  type: LoadBalancer